plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
highlighter: rouge
disqus: ape-1
include:
  - _pages
name: aprende.
logo: /assets/images/logo.png
permalink: /:title/
social:
  - title: Github
    icon: fa-github
    url: https://github.com/muhammedashfar7/mundana
  - title: Instagram
    icon: fa-instagram
    url: https://www.instagram.com/b.lan.c/
  - title: Twitter
    icon: fa-twitter
    url: https://twitter.com/ashfar_muhammed
  - title: Facebook
    icon: fa-facebook-square
    url: https://facebook.com/muhammed.ashfar.4/
markdown: kramdown
defaults:
  - scope:
      path: _authors
    values:
      layout: author
  - scope:
      path: _posts
    values:
      layout: post
      author: muhammedashfar
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: _pages
    values:
      layout: page
favicon: /assets/images/favicon.ico
collections:
  book_reviews:
    output: true
    output_ext: .html
    permalink: /book-reviews/:path/
  authors:
    output: true
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
paginate: 10
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
  - SECURITY.markdown
description: The place where you can read about all contents. Collecting the
  valuable information that our authors have and publishing each content to you.
baseurl: ""
email: aprende.blogs@gmail.com
mailchimp-list: https://subscribe.aprende.tk/in/
menu:
  - title: Home
    icon: icon-tv-2
    url: /
  - title: Blog
    icon: icon-single-copy-04
    url: /blog
  - title: Authors
    icon: icon-single-02
    url: /authors
  - title: Book Reviews
    url: /book-reviews
    icon: icon-bullet-list-67
  - title: Contact
    icon: icon-pencil
    url: /contact
