backend:
  name: git-gateway
  branch: gh-pages

publish_mode: editorial_workflow

media_folder: "assets/images"
collections:
  - label: "Site Configuration"
    name: "site_congfiguration"
    editor:
      preview: false
      delete: false
    files:
      - label: "Site Info"
        name: "site_info"
        file: "_config.yml"
        fields:
          - label: "Website Title"
            name: "name"
            widget: "string"
            required: true
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
            hint: "This will be displayed in search."
          - label: "Site Logo"
            name: "logo"
            widget: "image"
            required: false
          - label: "Favicon"
            name: "favicon"
            widget: "image"
            required: false
            hint: ".ico format recommended"
          - label: "Baseurl"
            name: "baseurl"
            widget: "string"
            required: false
            hint: "Enter the folder name where the site files are stored"
          - label: "Disqus Short Name"
            name: "disqus"
            widget: "string"
            required: false
            hint: "Ex: https://yourshortname.disqus.com"
          - label: "E-mail"
            name: "email"
            widget: "string"
            required: false
          - label: "Mailchimp List URL"
            name: "mailchimp-list"
            widget: "string"
            hint: "Ex: https://aprende.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
          - label: "Menu"
            name: "menu"
            widget: "list"
            required: true
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Icon Code"
                name: "icon"
                widget: "string"
                hint: "Find it on theme documentation."
              - label: "Menu URL"
                name: "url"
                widget: "string"
          - label: "Footer Social Icons"
            name: "social"
            widget: "list"
            required: true
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Icon Code"
                name: "icon"
                widget: "string"
                hint: "Find it on fontawesome icons. fab icons are used"
              - label: "Target URL"
                name: "url"
                widget: "string"
